/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GST_API_VERSION "1.0"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer gogst Plug-ins"

#define GST_PACKAGE_ORIGIN "https://github.com/bksworm/gst"

#define PACKAGE "gstgocallback-plugin"

#define PACKAGE_VERSION "1.16.2"

